In [6]:
import pandas as pd
import numpy as np
!pip install --upgrade numexpr

Requirement already satisfied: numexpr in d:\anaconda3\lib\site-packages (2.14.1)
Requirement already satisfied: numpy>=1.23.0 in d:\anaconda3\lib\site-packages (from numexpr) (2.4.2)

WARNING: Ignoring invalid distribution ~atplotlib (D:\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (D:\anaconda3\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (D:\anaconda3\Lib\site-packages)

In [7]:
df=pd.read_csv(r"C:\Users\Satish_Kundekar\Downloads\placement.csv")

In [8]:
df

    Unnamed: 0  cgpa     iq  placement
0            0   6.8  123.0          1
1            1   5.9  106.0          0
2            2   5.3  121.0          0
3            3   7.4  132.0          1
4            4   5.8  142.0          0
..         ...   ...    ...        ...
95          95   4.3  200.0          0
96          96   4.4   42.0          0
97          97   6.7  182.0          1
98          98   6.3  103.0          1
99          99   6.2  113.0          1

[100 rows x 4 columns]

In [9]:
df.head()

   Unnamed: 0  cgpa     iq  placement
0           0   6.8  123.0          1
1           1   5.9  106.0          0
2           2   5.3  121.0          0
3           3   7.4  132.0          1
4           4   5.8  142.0          0

In [10]:
df.shape

(100, 4)

In [11]:
# Steps of Build a Model

# 1. Preprocessing, EDA, Feature Selection
# 2. Extract input and output cols
# 3. Scale the values
# 4. Train Test Split
# 5. Train the Model
# 6. Evaluate the Model/ Model Selection
# 7. Deploy the Modell

In [12]:
# Preprocessing - Unwanted Coloumn removed

In [13]:
df.drop('Unnamed: 0',axis=1,inplace=True)

In [14]:
df

    cgpa     iq  placement
0    6.8  123.0          1
1    5.9  106.0          0
2    5.3  121.0          0
3    7.4  132.0          1
4    5.8  142.0          0
..   ...    ...        ...
95   4.3  200.0          0
96   4.4   42.0          0
97   6.7  182.0          1
98   6.3  103.0          1
99   6.2  113.0          1

[100 rows x 3 columns]

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cgpa       100 non-null    float64
 1   iq         100 non-null    float64
 2   placement  100 non-null    int64
dtypes: float64(2), int64(1)
memory usage: 2.5 KB

In [ ]:
!pip uninstall matplotlib

In [ ]:
!pip install matplotlib

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(df['cgpa'], df['iq'],c=df['placement'])

In [ ]:
x=df.iloc[:,0:2]

In [ ]:
x

In [ ]:
y=df.iloc[:,-1]

In [ ]:
y

In [ ]:
x.shape

In [ ]:
y.shape

In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1)

In [ ]:
x_train

In [ ]:
y_train

In [ ]:
x_test

In [ ]:
y_test

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler= StandardScaler()

In [ ]:
x_train= scaler.fit_transform(x_train)

In [ ]:
x_train

In [ ]:
x_test=scaler.transform(x_test)

In [ ]:
x_test

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
clf= LogisticRegression()

In [ ]:
# Model Training
clf.fit(x_train,y_train)

In [ ]:
y_pred=clf.predict(x_test)

In [ ]:
y_pred

In [ ]:
y_test

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test,y_pred)

In [ ]:
!pip install mlxtend

In [ ]:
from mlxtend.plotting import plot_decision_regions

In [ ]:
plot_decision_regions(X_train.values, y_train.values, clf=model, legend=2)